[tool.poetry]
name = "grid"
version = "0.1.0"
description = ""
authors = ["Noe Javet <javetnoe@students.zhaw.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
grid = "grid:main"

