[tool.poetry]
name = "frozenlake"
version = "0.1.0"
description = ""
authors = ["Noe Javet <javetnoe@students.zhaw.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gym = "^0.26.2"
pygame = "^2.6.1"
seaborn = "^0.13.2"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "frozenlake:main"
